ProjeOdevi/Controllers/ZimmetController.cs
using ProjeOdevi.Models;
using ProjeOdevi.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using ProjeOdevi.Security;

namespace ProjeOdevi.Controllers
{
    public class ZimmetController : Controller
    {
        ProjeOdeviDbEntities db = new ProjeOdeviDbEntities();
        KullaniciRoleProvider k = new KullaniciRoleProvider();
        // GET: Zimmet
        public ActionResult ParcaUrunZimmet()
        {
            var isim = k.BolumGetir(User.Identity.Name);
            var model = new ZimmetFormViewModel()
            {
                Urunler = db.Tbl_Urun.ToList(),
                BirimKullanicilari = db.Tbl_Kullanici.ToList(),
                Kullanicilar = db.Tbl_Kullanici.ToList(),
                Zimmetsiz = db.Tbl_Urun.ToList(),
                Bolum = isim[0].ToString()
            };
            return View(model);
        }

        public ActionResult ParcaUrunZimmetle(ZimmetFormViewModel model)
        {
            if (model.Tbl_Zimmet.ZimmetId == 0)
            {
                Tbl_Urun ZimmetlenecekUrun = db.Tbl_Urun.FirstOrDefault(x => x.UrunId == model.Tbl_Zimmet.UrunID);
                ZimmetlenecekUrun.Adet--;
                if (ZimmetlenecekUrun.Adet == 0)
                {
                    ZimmetlenecekUrun.ZimmetDurumu = true;
                }
                ZimmetlenecekUrun.ToptanFiyat = ZimmetlenecekUrun.ToptanFiyat - ZimmetlenecekUrun.BirimFiyat;

                Tbl_Zimmet Zimmetle = model.Tbl_Zimmet;
                Zimmetle.KullaniciID = model.Tbl_Zimmet.KullaniciID;
                Zimmetle.UrunID = model.Tbl_Zimmet.UrunID;
                Zimmetle.ArizaDurmu = false;
                Zimmetle.HazirPcParcalariID = null;
                db.Tbl_Zimmet.Add(Zimmetle);
                db.SaveChanges();
            }
            return RedirectToAction("ZimmetListesi");
        }

        public ActionResult HazirPcZimmet()
        {
            var model = new HazirPcZimmetViewModel()
            {
                HazirPc = db.Tbl_Urun.ToList(),
                Kullanicilar = db.Tbl_Kullanici.ToList(),
                Zimmetsiz = db.Tbl_Urun.ToList()
            };
            return View(model);
        }

        public ActionResult HazirPcZimmetle(HazirPcZimmetViewModel model)
        {
            if (model.Tbl_Zimmet.ZimmetId == 0)
            {
                Tbl_HazirPcParcalari ParcaZimmet = db.Tbl_HazirPcParcalari.FirstOrDefault(x => x.UrunID == model.Tbl_Zimmet.UrunID);
                int HazirPcParcalariID = ParcaZimmet.HazirPcParcalariId;
                Tbl_Urun ZimmetlenecekUrun = db.Tbl_Urun.FirstOrDefault(x => x.UrunId == model.Tbl_Zimmet.UrunID);
                ZimmetlenecekUrun.Adet--;
                if (ZimmetlenecekUrun.Adet==0)
                {
                    ZimmetlenecekUrun.ZimmetDurumu = true;
                }
                for (int i = 0; i < 4; i++)
                {
                    Tbl_Zimmet Zimmetle = model.Tbl_Zimmet;
                    Zimmetle.KullaniciID = model.Tbl_Zimmet.KullaniciID;
                    Zimmetle.UrunID = model.Tbl_Zimmet.UrunID;
                    Zimmetle.HazirPcParcalariID = HazirPcParcalariID;
                    Zimmetle.ArizaDurmu = false;
                    db.Tbl_Zimmet.Add(Zimmetle);
                    db.SaveChanges();
                    HazirPcParcalariID++;
                }
            }
            return RedirectToAction("Zimmetlistesi");
        }


        public ActionResult ZimmetListesi()
        {
            var model = db.Tbl_Zimmet.ToList();
            return View(model);
        }

        public ActionResult Arizalandi(int id)
        {
            var ZimmettenSil = db.Tbl_Zimmet.Find(id);
            ZimmettenSil.ArizaDurmu = true;
            db.SaveChanges();

            return RedirectToAction("ArizaliUrunler","Stok");
        }
    }
}

ProjeOdevi/Views/Zimmet/HazirPcZimmet.cshtml
@model ProjeOdevi.ViewModel.HazirPcZimmetViewModel

@{
    /**/

    ViewBag.Title = "HazirPc Zimmet";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

@using (Html.BeginForm("HazirPcZimmetle", "Zimmet", FormMethod.Post))
{
    <div class="panel panel-danger">
        <div class="panel-heading">
            Hazır Bilgisayar Parçaları
        </div>
        <div class="panel-body">
            <form role="form">
                <div class="form-group" id="Zimmet">
                    <label>Ürün Adı</label>
                    @{
                        foreach (var item in Model.HazirPc)
                        {
                            if (item.ZimmetDurumu == true || item.Adet == 0 || item.HazirPcMi == false)
                            {
                                Model.Zimmetsiz.Remove(item);
                            }
                        }
                    }
                    @Html.DropDownListFor(m => m.Tbl_Zimmet.UrunID, new SelectList(Model.Zimmetsiz, "UrunId", "Adi"), "Ürün Seçiniz", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Tbl_Zimmet.UrunID)
                </div>
                <div class="form-group">
                    <label>Personel Adı</label>
                    @Html.DropDownListFor(m => m.Tbl_Zimmet.KullaniciID, new SelectList(Model.Kullanicilar, "KullaniciId", "Adi"), "Kullanıcı Seçiniz", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Tbl_Zimmet.KullaniciID)
                </div>

                <button type="submit" class="btn btn-danger">Tamamla</button>

            </form>
        </div>
    </div>
}


@section script{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

ProjeOdevi/Views/Zimmet/ParcaUrunZimmet.cshtml
@model ProjeOdevi.ViewModel.ZimmetFormViewModel
@{
    /**/

    ViewBag.Title = "Parca Urun Zimmet";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

@using (Html.BeginForm("ParcaUrunZimmetle", "Zimmet", FormMethod.Post))
{
    <div class="panel panel-danger">
        <div class="panel-heading">
            Parça ürün zimmetle
        </div>
        <div class="panel-body">
            <form role="form" id="UrunZimmetle">
                <div class="form-group" id="Zimmet">
                    <label>Ürün Adı</label>
                    @{
                        foreach (var item in Model.Urunler)
                        {
                            if (item.ZimmetDurumu == true || item.HazirPcMi == true || item.Adet == 0)
                            {

                                Model.Zimmetsiz.Remove(item);
                            }
                        }

                        foreach (var k in Model.BirimKullanicilari)
                        {
                            if (k.Tbl_Bolum.BolumAdi != Model.Bolum && (!@HttpContext.Current.User.IsInRole("Admin") && !@HttpContext.Current.User.IsInRole("SatisYetkilisi")))
                            {

                                Model.Kullanicilar.Remove(k);
                            }
                        }
                    }

                    @Html.DropDownListFor(m => m.Tbl_Zimmet.UrunID, new SelectList(Model.Zimmetsiz, "UrunId", "Adi"), "Ürün Seçiniz", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Tbl_Zimmet.UrunID)
                </div>
                <div class="form-group">
                    <label>Personel Adı</label>
                    @Html.DropDownListFor(m => m.Tbl_Zimmet.KullaniciID, new SelectList(Model.Kullanicilar, "KullaniciId", "Adi"), "Kullanıcı Seçiniz", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Tbl_Zimmet.KullaniciID)
                </div>

                <button type="submit" class="btn btn-danger">Tamamla</button>

            </form>
        </div>
    </div>
}

@section script{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

ProjeOdevi/Views/Zimmet/ZimmetListesi.cshtml
@using ProjeOdevi.Models
@model List<Tbl_Zimmet>
@{
    ViewBag.Title = "ZimmetListesi";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="col-md-12">
    <!--   Kitchen Sink -->
    <div class="panel panel-danger">
        <div class="panel-heading">
            Zimmetli Ürünler
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover" id="tblZimmet">
                    <thead class="active-menu">
                        <tr>
                            <th>Adı</th>
                            <th>Soyadı</th>
                            <th>Zimmetli Ürün</th>
                            <th>Hazır Pc Parçaları</th>
                            <th>Barkot No</th>
                            <th>Arızalandı</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var zimmet in Model)
                        {
                            if (zimmet.ArizaDurmu == false)
                            {
                        <tr>
                            <td>@zimmet.Tbl_Kullanici.Adi</td>
                            <td>@zimmet.Tbl_Kullanici.Soyadi</td>
                            <td>@zimmet.Tbl_Urun.Adi</td>
                            @if (zimmet.Tbl_HazirPcParcalari != null)
                            {
                                <td>@zimmet.Tbl_HazirPcParcalari.ParcaAdi</td>
                            }
                            else
                            {
                                <td>-----</td>
                            }
                            <td>@zimmet.Tbl_Urun.BarkotNo</td>
                            <td><a class="btn btn-danger btnZimmetSil" data-id="@zimmet.ZimmetId">Arızalandı</a></td>
                        </tr>
                            }

                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- End  Kitchen Sink -->
</div>